import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { SECTION_TITLES } from '../../../../src/data/questions/section-titles'
import type { Question, RuleProcessingResult, ValidatedQuestion } from './types'

function complexityToDifficulty(c: 'simple' | 'complex'): 'easy' | 'medium' | 'hard' {
  return c === 'simple' ? 'easy' : 'medium'
}

// --- Deterministic shuffle -------------------------------------------------
// Fixes LLM positional bias (correct answer tends to land in option A/B).
// Seeded by `ruleNumber + question text` — stable across regenerations of the
// same question, distributes uniformly across 0..3 over many questions.
// NOTE: system.md forbids the LLM from referencing options by letter in the
// explanation so the shuffle cannot invalidate explanation content.

function fnv1aHash(s: string): number {
  let h = 2166136261 >>> 0
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 16777619) >>> 0
  }
  return h >>> 0
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6D2B79F5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function shuffleOptionsDeterministic(
  options: readonly string[],
  correctAnswer: number,
  seedKey: string,
): { options: string[]; correctAnswer: number } {
  const rand = mulberry32(fnv1aHash(seedKey))
  const indexed = options.map((item, originalIdx) => ({ item, originalIdx }))
  for (let i = indexed.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[indexed[i], indexed[j]] = [indexed[j], indexed[i]]
  }
  const shuffled = indexed.map((x) => x.item)
  const newCorrectIdx = indexed.findIndex((x) => x.originalIdx === correctAnswer)
  return { options: shuffled, correctAnswer: newCorrectIdx }
}

function materializeQuestion(
  v: ValidatedQuestion,
  section: string,
  indexInFile: number,
): Question {
  const sectionTitle = SECTION_TITLES[section]
  if (!sectionTitle) throw new Error(`Unknown section: ${section}`)
  const paddedIdx = String(indexInFile + 1).padStart(3, '0')

  // Deterministic shuffle of options to neutralize LLM positional bias.
  const { options, correctAnswer } = shuffleOptionsDeterministic(
    v.options,
    v.correctAnswer,
    `${v.ruleNumber}|${v.question}`,
  )

  return {
    id: `s${section}-${paddedIdx}`,
    section,
    sectionTitle,
    question: v.question,
    options,
    correctAnswer,
    explanation: v.explanation,
    difficulty: complexityToDifficulty(v.ruleComplexity),
    tags: [...v.tags],
    ruleReference: v.ruleReference,
    ruleComplexity: v.ruleComplexity,
  }
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function serializeQuestion(q: Question): string {
  const optionsLines = q.options.map((o) => `      \`${escapeString(o)}\``).join(',\n')
  const tagsLines = q.tags.map((t) => `'${t}'`).join(', ')
  const ruleRef = q.ruleReference ? `\n    ruleReference: '${q.ruleReference}',` : ''
  const ruleComplexity = q.ruleComplexity
    ? `\n    ruleComplexity: '${q.ruleComplexity}',`
    : ''
  return `  {
    id: '${q.id}',
    section: '${q.section}',
    sectionTitle: \`${escapeString(q.sectionTitle)}\`,
    question: \`${escapeString(q.question)}\`,
    options: [
${optionsLines},
    ],
    correctAnswer: ${q.correctAnswer},
    explanation: \`${escapeString(q.explanation)}\`,
    difficulty: '${q.difficulty}',
    tags: [${tagsLines}],${ruleRef}${ruleComplexity}
  }`
}

function renderFile(section: string, questions: Question[]): string {
  const sectionTitle = SECTION_TITLES[section]
  const header = [
    `import type { Question } from '../../lib/types'`,
    ``,
    `// =============================================================================`,
    `// SECTION ${section} — ${sectionTitle}`,
    `// Auto-generated by quiz-factory (${new Date().toISOString()})`,
    `// Source: /fuentes/Section ${section}-Canadian Electrical Code.pdf`,
    `// ${questions.length} questions covering ${new Set(questions.map((q) => q.ruleReference)).size} rules`,
    `// =============================================================================`,
    ``,
    `export const section${parseInt(section, 10)}QuizQuestions: Question[] = [`,
  ].join('\n')
  const body = questions.map(serializeQuestion).join(',\n')
  return `${header}\n${body},\n]\n`
}

export interface WriteOutputArgs {
  section: string
  outputPath: string
  errorsPath: string
  results: RuleProcessingResult[]
  overwrite: boolean
}

export interface WriteOutputReport {
  outputPath: string
  errorsPath: string | null
  written: number
  skipped: number
  errors: number
  finalQuestionCount: number
}

export function getExistingRuleNumbers(outputPath: string): Set<string> {
  const existing = readExistingQuestions(outputPath)
  const set = new Set<string>()
  for (const q of existing) if (q.ruleReference) set.add(q.ruleReference)
  return set
}

function readExistingQuestions(outputPath: string): Question[] {
  if (!existsSync(outputPath)) return []
  try {
    const raw = readFileSync(outputPath, 'utf8')
    const match = raw.match(/export const section\d+QuizQuestions:\s*Question\[\]\s*=\s*(\[[\s\S]*?\n\]);?/)
    if (!match) return []
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const arr = new Function(`return ${match[1]}`)()
    if (!Array.isArray(arr)) return []
    return arr as Question[]
  } catch {
    return []
  }
}

export function writeOutput(args: WriteOutputArgs): WriteOutputReport {
  mkdirSync(dirname(args.outputPath), { recursive: true })
  mkdirSync(dirname(args.errorsPath), { recursive: true })

  const existing = args.overwrite ? [] : readExistingQuestions(args.outputPath)
  const existingRules = new Set(existing.map((q) => q.ruleReference ?? ''))

  const newQuestions: Question[] = []
  let skipped = 0
  let errorCount = 0

  for (const r of args.results) {
    if (r.error) {
      errorCount++
      const line = JSON.stringify({
        timestamp: new Date().toISOString(),
        section: args.section,
        ruleNumber: r.ruleNumber,
        error: r.error.type,
        message: r.error.message,
        attempts: r.error.attempts,
        rawResponse: r.error.rawResponse,
      }) + '\n'
      appendFileSync(args.errorsPath, line, 'utf8')
    }
    for (const q of r.questions) {
      const ref = `Rule ${r.ruleNumber}`
      if (!args.overwrite && existingRules.has(ref)) {
        skipped++
        continue
      }
      newQuestions.push(q as unknown as Question)
    }
  }

  const merged: Question[] = [...existing]
  for (let i = 0; i < newQuestions.length; i++) {
    const v = newQuestions[i] as unknown as ValidatedQuestion
    const absoluteIndex = merged.length
    merged.push(materializeQuestion(v, args.section, absoluteIndex))
  }

  const content = renderFile(args.section, merged)
  writeFileSync(args.outputPath, content, 'utf8')

  return {
    outputPath: args.outputPath,
    errorsPath: errorCount > 0 ? args.errorsPath : null,
    written: newQuestions.length,
    skipped,
    errors: errorCount,
    finalQuestionCount: merged.length,
  }
}

export function defaultOutputPath(section: string, quizzesDir: string): string {
  return join(quizzesDir, `section-${section.padStart(2, '0')}.ts`)
}

export function defaultErrorsPath(section: string, quizzesDir: string): string {
  return join(quizzesDir, '_errors', `section-${section.padStart(2, '0')}-errors.jsonl`)
}
