import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { SECTION_TITLES } from '../../../../src/data/questions/section-titles'
import type { Question, RuleProcessingResult, ValidatedQuestion } from './types'

function complexityToDifficulty(c: 'simple' | 'complex'): 'easy' | 'medium' | 'hard' {
  return c === 'simple' ? 'easy' : 'medium'
}

function materializeQuestion(
  v: ValidatedQuestion,
  section: string,
  indexInFile: number,
): Question {
  const sectionTitle = SECTION_TITLES[section]
  if (!sectionTitle) throw new Error(`Unknown section: ${section}`)
  const paddedIdx = String(indexInFile + 1).padStart(3, '0')
  return {
    id: `s${section}-${paddedIdx}`,
    section,
    sectionTitle,
    question: v.question,
    options: [...v.options],
    correctAnswer: v.correctAnswer,
    explanation: v.explanation,
    difficulty: complexityToDifficulty(v.ruleComplexity),
    tags: [...v.tags],
    ruleReference: v.ruleReference,
    ruleComplexity: v.ruleComplexity,
  }
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function serializeQuestion(q: Question): string {
  const optionsLines = q.options.map((o) => `      \`${escapeString(o)}\``).join(',\n')
  const tagsLines = q.tags.map((t) => `'${t}'`).join(', ')
  const ruleRef = q.ruleReference ? `\n    ruleReference: '${q.ruleReference}',` : ''
  const ruleComplexity = q.ruleComplexity
    ? `\n    ruleComplexity: '${q.ruleComplexity}',`
    : ''
  return `  {
    id: '${q.id}',
    section: '${q.section}',
    sectionTitle: \`${escapeString(q.sectionTitle)}\`,
    question: \`${escapeString(q.question)}\`,
    options: [
${optionsLines},
    ],
    correctAnswer: ${q.correctAnswer},
    explanation: \`${escapeString(q.explanation)}\`,
    difficulty: '${q.difficulty}',
    tags: [${tagsLines}],${ruleRef}${ruleComplexity}
  }`
}

function renderFile(section: string, questions: Question[]): string {
  const sectionTitle = SECTION_TITLES[section]
  const header = [
    `import type { Question } from '../../lib/types'`,
    ``,
    `// =============================================================================`,
    `// SECTION ${section} — ${sectionTitle}`,
    `// Auto-generated by quiz-factory (${new Date().toISOString()})`,
    `// Source: /fuentes/Section ${section}-Canadian Electrical Code.pdf`,
    `// ${questions.length} questions covering ${new Set(questions.map((q) => q.ruleReference)).size} rules`,
    `// =============================================================================`,
    ``,
    `export const section${parseInt(section, 10)}QuizQuestions: Question[] = [`,
  ].join('\n')
  const body = questions.map(serializeQuestion).join(',\n')
  return `${header}\n${body},\n]\n`
}

export interface WriteOutputArgs {
  section: string
  outputPath: string
  errorsPath: string
  results: RuleProcessingResult[]
  overwrite: boolean
}

export interface WriteOutputReport {
  outputPath: string
  errorsPath: string | null
  written: number
  skipped: number
  errors: number
  finalQuestionCount: number
}

function readExistingQuestions(outputPath: string): Question[] {
  if (!existsSync(outputPath)) return []
  try {
    const raw = readFileSync(outputPath, 'utf8')
    const match = raw.match(/export const section\d+QuizQuestions:\s*Question\[\]\s*=\s*(\[[\s\S]*?\n\]);?/)
    if (!match) return []
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const arr = new Function(`return ${match[1]}`)()
    if (!Array.isArray(arr)) return []
    return arr as Question[]
  } catch {
    return []
  }
}

export function writeOutput(args: WriteOutputArgs): WriteOutputReport {
  mkdirSync(dirname(args.outputPath), { recursive: true })
  mkdirSync(dirname(args.errorsPath), { recursive: true })

  const existing = args.overwrite ? [] : readExistingQuestions(args.outputPath)
  const existingRules = new Set(existing.map((q) => q.ruleReference ?? ''))

  const newQuestions: Question[] = []
  let skipped = 0
  let errorCount = 0

  for (const r of args.results) {
    if (r.error) {
      errorCount++
      const line = JSON.stringify({
        timestamp: new Date().toISOString(),
        section: args.section,
        ruleNumber: r.ruleNumber,
        error: r.error.type,
        message: r.error.message,
        attempts: r.error.attempts,
        rawResponse: r.error.rawResponse,
      }) + '\n'
      appendFileSync(args.errorsPath, line, 'utf8')
    }
    for (const q of r.questions) {
      const ref = `Rule ${r.ruleNumber}`
      if (!args.overwrite && existingRules.has(ref)) {
        skipped++
        continue
      }
      newQuestions.push(q as unknown as Question)
    }
  }

  const merged: Question[] = [...existing]
  for (let i = 0; i < newQuestions.length; i++) {
    const v = newQuestions[i] as unknown as ValidatedQuestion
    const absoluteIndex = merged.length
    merged.push(materializeQuestion(v, args.section, absoluteIndex))
  }

  const content = renderFile(args.section, merged)
  writeFileSync(args.outputPath, content, 'utf8')

  return {
    outputPath: args.outputPath,
    errorsPath: errorCount > 0 ? args.errorsPath : null,
    written: newQuestions.length,
    skipped,
    errors: errorCount,
    finalQuestionCount: merged.length,
  }
}

export function defaultOutputPath(section: string, quizzesDir: string): string {
  return join(quizzesDir, `section-${section.padStart(2, '0')}.ts`)
}

export function defaultErrorsPath(section: string, quizzesDir: string): string {
  return join(quizzesDir, '_errors', `section-${section.padStart(2, '0')}-errors.jsonl`)
}
